### PR TITLE
Send analytics by GET instead of PUT

### PR DESCRIPTION
**Pull request by kelvin-chappell**
To avoid preflight OPTIONS request.

### CODE REVIEW

**Comment by jeteve** [comment]
Looks like PUT would not send a preflight OPTIONS request if the contentType is left to be application/x-www-form-urlencoded; charset=UTF-8  (reading http://api.jquery.com/jquery.ajax/ ).

Why turn it into a GET when you could just send the same payload ( a=<uri encoded value ) with a PUT (or POST)?

**Comment by janua** [comment]
A lot of analytics on the web are collected via `GET` including our own analytics.

About the domain it's posting to, what is it? Are we sending loads of unnecessary cookies along with the request?

**Comment by kelvin-chappell** [comment]
@janua It's using the ajax domain, and not setting any cookies.

**Comment by kelvin-chappell** [comment]
@jeteve To avoid the preflight I'd have to turn it into a POST and change the content type as you say.  Which is possibly better than a GET as it's a more accurate description of what's going on

@janua I think they're usually GETs because they're usually image beacons although Ophan does a GET.  I might find out why that is

**Comment by kelvin-chappell** [comment]
Yes Ophan is collecting by gif.
So I'll change to a POST and change content type.
This gives conditions for a simple request: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Pull request closed without merging**
