### PR TITLE
Update guAnalyticsAdapter to handle Ozone

### PR DESCRIPTION
**Pull request by janua**
## Ozone adapter

When we use the Ozone adapter, it is facilitating server side header bidding via them to different integrations. When one of these integrations has a bid available via Ozone, we report it via our `guAnalyticsAdapter` that there is a bid available.
Unfortunately this is only reported as the adapter that has the bid, which is currently just `ozone`. 

However, when there is a bid available from Ozone, we are able to tell which integration it has come from via `adserverTargeting.oz_winner`.

## Fix

When there is a `bidderCode` available we check if it is `ozone` and if it is, append the `oz_winner` to the `bidderCode`.

@guardian/commercial-dev @kelvin-chappell

### CODE REVIEW

**Comment by janua** [comment]
@jeteve None of the functions in this module are unit tested!

**Comment by kelvin-chappell** [comment]
@janua https://github.com/guardian/Prebid.js/blob/master/test/spec/modules/guAnalyticsAdapter_spec.js

**Comment by janua** [comment]
@kelvin-chappell Thanks, I know about this spec file! However I was only talking about unit tests...

**Comment by janua** [comment]
@kelvin-chappell Now with both integration tests and units tests!

**Pull request merged**
